-- SCHEMA: settings

CREATE SCHEMA IF NOT EXISTS settings;

GRANT ALL ON SCHEMA settings TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA settings GRANT ALL PRIVILEGES ON TABLES TO admin;

-- SCHEMA: language

CREATE SCHEMA IF NOT EXISTS language;

GRANT ALL ON SCHEMA language TO postgres;

GRANT USAGE ON SCHEMA language TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA language GRANT ALL PRIVILEGES ON TABLES TO admin;

-- SCHEMA: navigation

CREATE SCHEMA IF NOT EXISTS navigation;

GRANT ALL ON SCHEMA navigation TO postgres;

GRANT USAGE ON SCHEMA navigation TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA navigation GRANT ALL PRIVILEGES ON TABLES TO admin;

GRANT USAGE ON SCHEMA navigation TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA navigation GRANT SELECT ON TABLES TO readonly;

-- SCHEMA: cache

CREATE SCHEMA IF NOT EXISTS cache;

GRANT ALL ON SCHEMA cache TO postgres;

GRANT USAGE ON SCHEMA cache TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA cache GRANT SELECT ON TABLES TO readonly;

-- SCHEMA: prototype

CREATE SCHEMA IF NOT EXISTS prototype;

GRANT ALL ON SCHEMA prototype TO postgres;

GRANT USAGE ON SCHEMA prototype TO public;

GRANT USAGE ON SCHEMA prototype TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA prototype GRANT SELECT ON TABLES TO readonly;

-- SCHEMA: presentation

CREATE SCHEMA IF NOT EXISTS presentation;

GRANT ALL ON SCHEMA presentation TO postgres;

GRANT USAGE ON SCHEMA presentation TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA presentation GRANT ALL PRIVILEGES ON TABLES TO admin;

GRANT USAGE ON SCHEMA presentation TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA presentation GRANT SELECT ON TABLES TO readonly;

-- SCHEMA: media

CREATE SCHEMA IF NOT EXISTS media;

GRANT ALL ON SCHEMA media TO postgres;

GRANT USAGE ON SCHEMA media TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA media GRANT ALL PRIVILEGES ON TABLES TO admin;

GRANT USAGE ON SCHEMA media TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA media GRANT SELECT ON TABLES TO readonly;

-- SCHEMA: auth

CREATE SCHEMA IF NOT EXISTS auth;

GRANT ALL ON SCHEMA auth TO postgres;

GRANT USAGE ON SCHEMA auth TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL PRIVILEGES ON TABLES TO admin;