-- CREATE VIEW navigation.route_layout_page AS
-- SELECT
--     r.id,
--     r.parent_id,
--     r.url_name,
--     r.ui_name,
--     r.meta_description,
--     r.meta_keywords,
--     r.url_type,
--     r.render_method,
--     COALESCE(rl.layout_id, NULL) AS layout_id,
--     COALESCE(rp.id, NULL) AS page_id
-- FROM
--     navigation.route r
-- LEFT JOIN
--     presentation.route_layout_type rl
-- ON
--     r.id = rl.route_id
-- LEFT JOIN
--     presentation.route_template_instance rp
-- ON
--     r.id = rp.route_id;

-- CREATE VIEW presentation.route_page_template AS
-- SELECT
--     rti.route_id,
--     rti.template_instance_order,
--     rti.json_data,
--     tt.url_name
-- FROM presentation.route_template_instance rti
-- LEFT JOIN types.template_type tt 
--     ON rti.template_type_id = tt.id
-- ORDER BY rti.template_instance_order ASC;

-- CREATE VIEW presentation.route_layout_type_url AS
-- SELECT
--     rl.route_id,
-- 	lt.url_name
-- FROM presentation.route_layout_type rl
-- LEFT JOIN types.layout_type lt 
--     ON rl.layout_id = lt.id;