-- Create roles - procedual approach
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'admin') THEN
        CREATE ROLE admin WITH LOGIN PASSWORD 'admin';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'customer') THEN
        CREATE ROLE customer WITH LOGIN PASSWORD 'customer';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'client') THEN
        CREATE ROLE client WITH LOGIN PASSWORD 'client';
    END IF;
END $$;

GRANT USAGE ON SCHEMA navigation TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA admin GRANT ALL PRIVILEGES ON TABLES TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA navigation GRANT ALL PRIVILEGES ON TABLES TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA customer GRANT ALL PRIVILEGES ON TABLES TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA settings GRANT ALL PRIVILEGES ON TABLES TO admin;

GRANT USAGE ON SCHEMA customer TO customer;
ALTER DEFAULT PRIVILEGES IN SCHEMA customer GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO customer;

GRANT USAGE ON SCHEMA navigation TO client;
ALTER DEFAULT PRIVILEGES IN SCHEMA navigation GRANT SELECT ON TABLES TO client;

GRANT USAGE ON SCHEMA cache TO client;
ALTER DEFAULT PRIVILEGES IN SCHEMA cache GRANT SELECT ON TABLES TO client;

