-- Drop the public schema if it exists

DROP SCHEMA IF EXISTS public;

-- SCHEMA: admin

CREATE SCHEMA IF NOT EXISTS admin;

GRANT ALL ON SCHEMA admin TO postgres;

GRANT USAGE ON SCHEMA admin TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA admin GRANT ALL PRIVILEGES ON TABLES TO admin;

-- SCHEMA: navigation

CREATE SCHEMA IF NOT EXISTS navigation;

GRANT ALL ON SCHEMA navigation TO postgres;

GRANT USAGE ON SCHEMA navigation TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA navigation GRANT ALL PRIVILEGES ON TABLES TO admin;

GRANT USAGE ON SCHEMA navigation TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA navigation GRANT SELECT ON TABLES TO readonly;

-- SCHEMA: customer

CREATE SCHEMA IF NOT EXISTS customer;

GRANT ALL ON SCHEMA customer TO postgres;

GRANT USAGE ON SCHEMA customer TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA customer GRANT ALL PRIVILEGES ON TABLES TO admin;

GRANT USAGE ON SCHEMA customer TO customer;
ALTER DEFAULT PRIVILEGES IN SCHEMA customer GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO customer;

-- SCHEMA: settings

CREATE SCHEMA IF NOT EXISTS settings;

GRANT ALL ON SCHEMA settings TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA settings GRANT ALL PRIVILEGES ON TABLES TO admin;

-- SCHEMA: cache

CREATE SCHEMA IF NOT EXISTS cache;

GRANT ALL ON SCHEMA cache TO postgres;

GRANT USAGE ON SCHEMA cache TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA cache GRANT SELECT ON TABLES TO readonly;

-- SCHEMA: types

CREATE SCHEMA IF NOT EXISTS types;

GRANT USAGE ON SCHEMA types TO public;